-- Sequence : 순차번호 생성기. 대부분 인위적인 PK 사용용도
DROP SEQUENCE FRIEND_SEQ;
CREATE SEQUENCE FRIEND_SEQ
    START WITH 1 -- 1부터 시작(기본값)
    INCREMENT BY 1 -- 1씩 증가(기본값)
    MAXVALUE 9999 -- 최대값
    MINVALUE 1 -- 최소값
    NOCYCLE -- CYCLE : 순차번호 9999 -> 1
    NOCACHE; 
SELECT FRIEND_SEQ.NEXTVAL FROM DUAL; -- 다음 순차번호 값
SELECT FRIEND_SEQ.CURRVAL FROM DUAL; -- 현재 시퀀스 값

DROP TABLE FRIEND;
CREATE TABLE FRIEND(
    NO NUMBER(5) PRIMARY KEY,
    NAME VARCHAR2(50) NOT NULL,
    TEL VARCHAR2(20) UNIQUE,
    ADDRESS VARCHAR2(250),
    LAST_MODIFY DATE DEFAULT SYSDATE
);
DROP SEQUENCE FRIEND_SEQ;
CREATE SEQUENCE FRIEND_SEQ
    MAXVALUE 99999
    NOCACHE NOCYCLE;
SELECT * FROM FRIEND;
INSERT INTO FRIEND (NO, NAME, TEL, ADDRESS)
    VALUES(FRIEND_SEQ.NEXTVAL, '홍길동', '010-9999-9999', '서울');
INSERT INTO FRIEND (NO, NAME, TEL, ADDRESS)
    VALUES(FRIEND_SEQ.NEXTVAL, '김길동', '010-8888-9999', '서울');
INSERT INTO FRIEND (NO, NAME, TEL, ADDRESS)
    VALUES(FRIEND_SEQ.NEXTVAL, '김길동', NULL, '서울');
SELECT * FROM FRIEND;
DELETE FROM FRIEND WHERE TEL IS NULL;

DROP TABLE DEPT CASCADE CONSTRAINTS; -- 비추

-- 연습문제
DROP TABLE MEMBER;
DROP TABLE MEMBER_LEVEL;
DROP SEQUENCE MEMBER_MNO_SQ;
CREATE TABLE MEMBER_LEVEL(
    LEVELNO NUMBER(2),
    LEVELNAME VARCHAR2(30) NOT NULL,
    PRIMARY KEY(LEVELNO)
);
CREATE TABLE MEMBER(
    mNO NUMBER(3),
    mNAME VARCHAR2(200) NOT NULL,
    mPW VARCHAR2(50) NOT NULL,
    mEMAIL VARCHAR2(250),
    mPOINT NUMBER(5),
    mRDATE DATE DEFAULT SYSDATE,
    LEVELNO NUMBER(2),
    PRIMARY KEY(mNO),
    CHECK(mPOINT>=0),
    FOREIGN KEY (LEVELNO) REFERENCES MEMBER_LEVEL (LEVELNO)
);
CREATE SEQUENCE MEMBER_MNO_SQ
    MAXVALUE 999
    NOCACHE NOCYCLE;
-- INSERT INTO MEMBER_LEVEL ~
SELECT * FROM MEMBER_LEVEL;
INSERT INTO MEMBER_LEVEL
    VALUES (-1, 'black');
INSERT INTO MEMBER_LEVEL
    VALUES (0, '일반');
INSERT INTO MEMBER_LEVEL
    VALUES (1, '실버');
INSERT INTO MEMBER_LEVEL
    VALUES (2, '골드');
-- INSERT INTO MEMBER ~
SELECT * FROM MEMBER;
INSERT INTO MEMBER (MNO, MNAME, MPW, MEMAIL, MPOINT, MRDATE, LEVELNO)
    VALUES (MEMBER_MNO_SQ.NEXTVAL, '홍길동', 'aa', 'hong@hong.com', 0, '21/09/26', 0);
-- TO_DATE('21/09/26', 'RR/MM/DD') 쓰는게 좋음
INSERT INTO MEMBER (MNO, MNAME, MPW, MEMAIL, MPOINT, MRDATE, LEVELNO)
    VALUES (MEMBER_MNO_SQ.NEXTVAL, '신길동', 'bb', 'sin@sin.com', 1000, '22/04/01', 1);
-- 연습문제와 같이 출력되도록 SELECT (EQUI JOIN)
SELECT MNO, MNAME, TO_CHAR(MRDATE, 'YYYY-MM/DD') AS MRDATE, MEMAIL AS MMAIL, MPOINT AS POINT, LEVELNAME||'고객' AS LEVELNAME
    FROM MEMBER M, MEMBER_LEVEL ML
    WHERE M.LEVELNO = ML.LEVELNO;